apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fast-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fast-api
    spec:
      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "poetry", "run","fastapi", "run","src/celery_sandbox/app.py", "--port", "5000" ]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
          ports:
            - containerPort: 5000
              protocol: TCP
