name: "Install AWS CLI"
description: "Action to install AWS CLI"
branding:
  icon: "code"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      name: Install AWS CLI
      shell: bash
