name: "Install AWS CLI"
description: "Action to install AWS CLI"
branding:
  icon: "code"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Deploying to ${{inputs.environment}}..."
        sleep ${{inputs.wait}}
      name: Deploy to ${{inputs.environment}}
      shell: bash
