apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: basic-auth
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: basic-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: javier/days-since/basic-auth
        property: auth
