services:
  postgres:
    container_name: postgres
    image: postgres:17.0-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  backstage:
    container_name: backstage
    pull_policy: build
    restart: always
    env_file:
      - .env

    build:
        context: .
        dockerfile: packages/backend/Dockerfile
        no_cache: false
    ports:
      - 7007:7007
