---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: datahub-secrets
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: javier/databhub/mysql
        property: mysql-root-password

    - secretKey: mysql-password
      remoteRef:
        key: javier/databhub/mysql
        property: mysql-password

    - secretKey: neo4j-password
      remoteRef:
        key: javier/datahub/neo4j
        property: neo4j-password

    - secretKey: NEO4J_AUTH
      remoteRef:
        key: javier/datahub/neo4j
        property: NEO4J_AUTH

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datahub-users-secret
spec:
    refreshInterval: 24h
    secretStoreRef:
        name: cluster-secretstore
        kind: ClusterSecretStore
    target:
      name: datahub-users-secret
      creationPolicy: Owner
    data:
      - secretKey: user.props
        remoteRef:
          key: javier/datahub/frontend
          property: demo-user
