---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: mysql-secrets
    creationPolicy: Owner
  data:
    - secretKey: mysql-root-password
      remoteRef:
        key: javier/databhub/mysql
        property: mysql-root-password

    - secretKey: mysql-password
      remoteRef:
        key: javier/databhub/mysql
        property: mysql-password


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: neo4j-secrets
    creationPolicy: Owner
  data:
    - secretKey: neo4j-password
      remoteRef:
        key: javier/datahub/neo4j
        property: neo4j-password
    - secretKey: NEO4J_AUTH
      remoteRef:
        key: javier/datahub/neo4j
        property: NEO4J_AUTH


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datahub-users-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: datahub-users-secret
    creationPolicy: Owner
  data:
    - secretKey: user.props
      remoteRef:
        key: javier/datahub/frontend
        property: demo-user

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
  data:
    - secretKey: docker-username
      remoteRef:
        key: javier/docker/jmatiastw
        property: username
    - secretKey: docker-password
      remoteRef:
        key: javier/docker/jmatiastw
        property: password
    - secretKey: docker-email
      remoteRef:
        key: javier/docker/jmatiastw
        property: email
