graph TD
    US("Jira User Story: PLAT-2000<br>Repository: git\@github.com/jmatias/lol-im-not-really-a-repo")
    PRCRDEV1("Code Review (PR ID: PR-400)<br>branch: feature/PLAT-2000-feature → dev<br>reviewer: teammate\@abbive.com<br>Repository: git\@github.com/jmatias/lol-im-not-really-a-repo<br>git commit SHA: badbadf00d")
    TESTDEV1("Dev Unit Test (test_id: TEST-3000)<br>passed: 106, failed: 0, coverage_percent: 92.71<br>evidence blob: EV-4000<br>blob url: s3://evidence_vault/raw/EV-4000/TEST-3000-results.xml")
    DEVDEPLOY("Deployment to DEV<br>deployment_id: DEPLOYMENT-0001<br>timestamp: 2025-04-18T06-41-37.652049<br>cr_id: N/A")
    TESTDEV2("Dev Integration Test (test_id: TEST-3001)<br>passed: 101, failed: 0, coverage_percent: 94.7<br>evidence blob:EV-4001<br>blob url: s3://evidence_vault/raw/EV-4001/TEST-3001-results.xml")
    PRCRMAIN("Code Review<br>branch: dev → main<br>reviewer: another.dev\@abbvie.com<br>Repository: git\@github.com/jmatias/lol-im-not-really-a-repo<br>PR ID: PR-123<br>git commit SHA: abdcef1234")
    TESTPREQ("PREQ Integration Test (test_id: TEST-3002)<br>passed: 99, failed: 0, coverage_percent: 90.12<br>evidence blob: EV-4002<br>url: s3://evidence_vault/raw/EV-4002/TEST-3002-results.xml")
    PREQDEPLOY("Deployment to PREQ<br>deployment_id: DEPLOYMENT-0002<br>timestamp: 2025-04-18T06-41-37.652049<br>cr_id: N/A")
    QADEPLOY("Deploy to QA (cr_id: SNOWQA2000)<br>status: approved<br>approved_by: manager\@abbvie.com<br>approved_at: 2025-04-18T07:41:37.652049Z<br>evidence blob: EV-4006<br>blob url: s3://evidence_vault/raw/EV-4006/SNOWQA2000.txt")
    TESTQA("QA Integration Test (test_id: TEST-3003)<br>passed: 141, failed: 0, coverage_percent: 97.29<br>evidence blob: EV-4003<br>blob url: s3://evidence_vault/raw/EV-4003/TEST-3003-results.xml")
    PRODDEPLOY("Deploy to PROD (cr_id: SNOWPROD2001), status: approved<br>approved_by: manager\@abbvie.com<br>approved_at: 2025-04-18T08:41:37.652049Z<br>evidence blob: EV-4007<br>blob url: s3://evidence_vault/raw/EV-4007/SNOWPROD2001.txt")
    TESTPROD("PROD Integration Test (test_id: TEST-3004)<br>passed: 138, failed: 1,coverage_percent: 85.32<br>evidence blob: EV-4004<br>blob url: s3://evidence_vault/raw/EV-4004/TEST-3004-results.xml")

    US --> PRCRDEV1
    PRCRDEV1 --> TESTDEV1
    TESTDEV1 --> DEVDEPLOY
    DEVDEPLOY --> TESTDEV2
    TESTDEV2 --> PRCRMAIN
    PRCRMAIN --> PREQDEPLOY
    PREQDEPLOY --> TESTPREQ
    TESTPREQ --> QADEPLOY
    QADEPLOY --> TESTQA
    TESTQA --> PRODDEPLOY
    PRODDEPLOY --> TESTPROD
