apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdlc-trace-pvc
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: 1Gi
  storageClassName: auto-ebs-sc
