apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdlc-trace
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sdlc-trace
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdlc-trace
    spec:
      serviceAccountName: {{ include "sdlc-trace.serviceAccountName" . }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: sdlc-trace-pvc
      initContainers:
        - name: init-mydata
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "sh", "-c", "mkdir -p /code/data; cp -rfv /code/sdlc_trace/data/* /code/data/" ]
          volumeMounts:
            - name: data-volume
              mountPath: /code/data
      containers:
        - name: {{ .Chart.Name }}
          command: [ "poetry","run","fastapi", "run", "sdlc_trace/main.py", "--port", "8000", "--host","0.0.0.0" ]

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STORAGE_ROOT
              value: "/code/data"

          volumeMounts:
            - name: data-volume
              mountPath: /code/data
          ports:
            - containerPort: 8000
              protocol: TCP

          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe: {{ toYaml .Values.startupProbe | nindent 12 }}

          resources: {{ toYaml .Values.resources | nindent 12 }}
