apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdlc-trace
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sdlc-trace
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdlc-trace
    spec:
      serviceAccountName: {{ include "sdlc-trace.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: {{ .Chart.Name }}
          command: [ "poetry","run","fastapi", "run", "sdlc_trace/main.py", "--port", "8000", "--host","0.0.0.0" ]


          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: []

          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
