# nonk8s
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: javier-sandbox-eks
  region: "us-east-1"
  version: "1.32"


availabilityZones: [ "us-east-1a","us-east-1b" ]


managedNodeGroups:
  - name: mng2-spot
    instanceTypes: [ "m5.xlarge" ] # At least one instance type should be specified
    minSize: 1
    desiredCapacity: 1
    maxSize: 5
    spot: true
    availabilityZones:
      - "us-east-1a"
    nodeRepairConfig:
      enabled: true
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: false
        cloudWatch: true

      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

        # For dev only
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  - name: mng1
    instanceTypes: [ "m5.xlarge" ] # At least one instance type should be specified
    minSize: 0
    desiredCapacity: 0
    maxSize: 2
    spot: false
    availabilityZones:
      - "us-east-1a"
    nodeRepairConfig:
      enabled: true
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: false
        cloudWatch: true

      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

        # For dev only
        - arn:aws:iam::aws:policy/AmazonS3FullAccess


fargateProfiles:
#  - name: fp-default
#    selectors:
#      # All workloads in the "default" Kubernetes namespace will be
#      # scheduled onto Fargate:
#      - namespace: default
#      # All workloads in the "kube-system" Kubernetes namespace will be
#      # scheduled onto Fargate:
#      - namespace: kube-system
  - name: fp
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: celery-sandbox
        labels:
          env: dev
    tags:
      env: dev
      name: fp-dev


  - name: fp-kube-system
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: kube-system
    tags:
      env: dev
      name: fp-dev



iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: external-secrets-sa
        namespace: external-secrets
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

    - metadata:
        name: prometheus-sa
        namespace: monitoring
      attachPolicyARNs:
        # For dev only
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

    - metadata:
        name: eksctl-sa
        namespace: monitoring
      attachPolicyARNs:
        # For dev only
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

    - metadata:
        name: eksctl-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

    - metadata:
        name: eksctl-sa
        namespace: argocd
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

addons:

  #  - name: amazon-cloudwatch-observability
  #  - name: prometheus-node-exporter
  - name: vpc-cni
    version: latest

  - name: aws-ebs-csi-driver

  - name: aws-mountpoint-s3-csi-driver

  - name: eks-node-monitoring-agent

  - name: metrics-server

  - name: external-dns
    version: latest

  - name: cert-manager
    version: latest

  - name: eks-pod-identity-agent
    version: latest


addonsConfig:
  autoApplyPodIdentityAssociations: true
