# nonk8s
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: javier-sandbox-eks
  region: "us-east-1"
  version: "1.33"

autoModeConfig:
  enabled: true
  nodePools:
    - general-purpose

availabilityZones: [ "us-east-1a","us-east-1b" ]


iam:
  withOIDC: true

  serviceAccounts:

    - metadata:
        name: argocd-ecr-readonly
        namespace: argocd
      roleName: argocd-ecr-readonly
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

    - metadata:
        name: celery-sandbox-s3-readonly
        namespace: celery-sandbox
      roleName: celery-sandbox-s3-readonly-role
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

    - metadata:
        name: github-actions-sa
        namespace: github-actions
      roleName: github-actions-sa-role
      wellKnownPolicies:
        imageBuilder: true

    - metadata:
        name: javier-runner-gha-rs-no-permission
        namespace: github-actions
      roleName: javier-runner-gha-rs-no-permission-role
      wellKnownPolicies:
        imageBuilder: true

    - metadata:
        name: external-secrets
        namespace: external-secrets
      roleName: external-secrets-sa-role
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
              - secretsmanager:ListSecrets
              - secretsmanager:ListSecretVersionIds
            Resource: "*"



managedNodeGroups: [ ]
fargateProfiles: [ ]


addons:

  - name: eks-node-monitoring-agent
    version: latest

  - name: metrics-server
    version: latest

  - name: kube-state-metrics
    version: latest


#  - name: aws-ebs-csi-driver
#    version: latest
#    wellKnownPolicies:
#      ebsCSIController: true
#    resolveConflicts: overwrite
#    configurationValues: |-
#      controller:
#        resources: {}

  - name: aws-mountpoint-s3-csi-driver
    version: latest


  - name: external-dns
    version: latest
#    configurationValues: |-
#      interval: "20s"
#      policy: sync
#      serviceMonitor:
#        enabled: true
#    resolveConflicts: overwrite

  - name: cert-manager
    version: latest
    wellKnownPolicies:
      certManager: true
    configurationValues: |-
      replicaCount: 2

      resources: {}

      cainjector:
        replicaCount: 2
        resources: {}

      webhook:
        replicaCount: 2
        resources: {}

    resolveConflicts: overwrite

  - name: eks-pod-identity-agent
    version: latest


addonsConfig:
  autoApplyPodIdentityAssociations: true
