apiVersion: v1
kind: Service
metadata:
  name: {{ include "celery-sandbox.fullname" . }}
  labels:
    {{- include "celery-sandbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    {{- include "celery-sandbox.selectorLabels" . | nindent 4 }}
