helm:
  parameters:
  - name: image.name
    value: docker.io/mher/flower
    forcestring: true
  - name: image.tag
    value: 0.6.2
    forcestring: true
  - name: flower.image.tag
    value: 2.0.1
    forcestring: true
