image:
  repository: 590184073526.dkr.ecr.us-east-1.amazonaws.com/javier/celery-sandbox
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.3.0"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: { }

resources: { }

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: { }

redis:
  url : "redis://redis:6379/0"

flower:
  enabled: true

environment: "local"

ingress:
  enabled: true
