apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD

    - secretKey: password
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD
