apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yaml

helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd-image-updater
    namespace: argocd
    version: 0.*
    valuesFile: values.yaml
