---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: javier/docker/jmatiastw
        property: username
    - secretKey: password
      remoteRef:
        key: javier/docker/jmatiastw
        property: password
