{{ if .Values.airflow.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: 386757133934.dkr.ecr.us-east-1.amazonaws.com/docker-hub/apache/airflow
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/airflow
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    automated:
      prune: true
      enabled: {{ .Values.airflow.autoSync }}
      selfHeal: {{ .Values.airflow.autoSync }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 10

{{- end }}
