apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/app-of-apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    {{ if .Values.appOfApps.autoSync }}
    automated:
      enabled: false
      prune: true
      selfHeal: false
      allowEmpty: false
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m0s
      limit: 15
