apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argcd-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: manifests/crds
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: v3.*

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
