apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: quay.io/argoprojlabs/argocd-image-updater,
      386757133934.dkr.ecr.us-east-1.amazonaws.com/quay/argoprojlabs/argocd-image-updater
    argocd-image-updater.argoproj.io/update-strategy: semver
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/argocd-image-updater
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    kustomize:
      namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{ if .Values.argocdImageUpdater.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
