{{ if .Values.backstage.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: backstage=386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/backstage:0.*
    argocd-image-updater.argoproj.io/backstage.helm.image-tag: backstage.image.tag
    argocd-image-updater.argoproj.io/update-strategy: semver
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: infra/apps/backstage
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        valueFiles:
          - values.yaml
          - values-override.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{ if .Values.backstage.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

{{- end}}
