{{ if .Values.datahub.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: frontend=acryldata/datahub-frontend-react
    argocd-image-updater.argoproj.io/frontend.helm.image-name: datahub-frontend.image.repository
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - path: infra/apps/datahub
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    helm:
      releaseName: datahub

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
      - ServerSideApply=false

    {{ if .Values.datahub.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m0s

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: datahub-auth-secrets
      namespace: datahub
      jsonPointers:
        - /data/system_client_secret
        - /data/token_service_salt
        - /data/token_service_signing_key
    - group: ""
      kind: Secret
      name: datahub-encryption-secrets
      namespace: datahub
      jsonPointers:
        - /data/encryption_key_secret
    - group: ""
      kind: Secret
      name: datahub-gms-secret
      namespace: datahub
      jsonPointers:
        - /data/datahub.gms.secret

{{- end }}
