{{ if .Values.datahub.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datahub
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/frontend.helm.image-name: datahub-frontend.image.repository
    argocd-image-updater.argoproj.io/frontend.helm.image-tag: datahub-frontend.image.tag
    argocd-image-updater.argoproj.io/gms.helm.image-name: datahub-gms.image.repository
    argocd-image-updater.argoproj.io/gms.helm.image-tag: datahub-gms.image.tag
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datahub
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/datahub
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main
    kustomize:
      namespace: datahub


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=false
      - ServerSideApply=false

    {{ if .Values.datahub.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m0s


{{- end }}
