{{ if .Values.daysSince.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: days-since
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: 386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/days-since
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: days-since
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/days-since
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        replicaCount: 2

        image:
          repository: 386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/days-since
          tag: {{ .Values.daysSince.image.tag }}
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          className: "alb"
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: 'ip'
            alb.ingress.kubernetes.io/group.name: "sandbox-external"
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/f3618733-cee3-4704-8bb3-2ba753cbd56e
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
            external-dns.alpha.kubernetes.io/hostname: ashley.tw-javier.work
            external-dns.alpha.kubernetes.io/ttl: "60"
          hosts:
            - host: ashley.tw-javier.work
              paths:
                - path: /
                  pathType: Prefix
          tls: [ ]


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{ if .Values.daysSince.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

{{- end}}
