{{ if .Values.externalSecrets.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: oci.external-secrets.io/external-secrets/external-secrets:^0.18
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/external-secrets
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
      - Replace=false
    automated:
      prune: true
      selfHeal: true

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      name: external-secrets
      namespace: external-secrets
      jsonPointers:
        - /metadata/annotations/eks.amazonaws.com/role-arn
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/decodingStrategy

{{- end }}
