{{- if eq (lower .Values.environment) "aws" }}
{{ if .Values.externalSecrets.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/external-secrets
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
    automated:
      prune: true
      selfHeal: true

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
{{- end }}
{{- end }}
