{{ if .Values.actionsRunnerController.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-ss
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: ghcr.io/actions/actions-runner:^0.12
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd.argoproj.io/sync-wave: "2"

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:

  destination:
    namespace: github-actions
    server: {{ .Values.spec.destination.server }}

  project: default

  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.12.*

    helm:
      releaseName: javier-runner

      valuesObject:

        runnerGroup: javier-k8s-runner-group
        runnerScaleSetName: javier-runner

        githubConfigUrl: https://github.com/jmatiascabrera
        githubConfigSecret: github-auth

        controllerServiceAccount:
          namespace: github-actions
          name: github-actions-sa

        ## Because we are using docker-in-docker, the helm chart is applying
        ## the service account {releaseName}-gha-rs-no-permission-role
        ## even though you don't specify it here.

        containerMode:
          type: "dind" #docker-in-docker

        maxRunners: 10


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    {{- if .Values.actionsRunnerController.autoSync }}
    automated:
      prune: true
      selfHeal: true

    {{- end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
      limit: 10
{{- end }}
