{{ if .Values.actionsRunnerController.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: github-actions
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/gha-runner-config
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      namespace: github-actions

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{- if .Values.actionsRunnerController.autoSync }}
    automated:
      prune: true
      selfHeal: true

    {{- end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
      limit: 10
{{- end }}
