{{ if .Values.actionsRunnerController.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-ss-controller
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  
  destination:
    namespace: github-actions
    server: {{ .Values.spec.destination.server }}
  
  project: default
  
  source:
    path: infra/apps/gha-runner-scale-set-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main



  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    {{- if .Values.actionsRunnerController.autoSync }}
    automated:
      prune: true
      selfHeal: true

    {{- end }}

    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 15
{{- end }}
