{{ if .Values.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: public.ecr.aws/grafana/grafana:^12.0,
      quay.io/prometheus/prometheus:^3.4.1, quay.io/prometheus-operator/prometheus-operator:^0,
      quay.io/prometheus/node-exporter:^1,
      quay.io/prometheus/alertmanager:^0
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/prometheus
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=false

    {{ if .Values.prometheus.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

{{- end }}
