{{ if .Values.unleash.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: public.ecr.aws/unleashorg/unleash-server
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: unleash
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/unleash
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main


  syncPolicy:
    retry:
      limit: 6
      backoff:
        duration: "30s"

    {{ if .Values.unleash.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    syncOptions:
      - CreateNamespace=true

{{ end }}
