{{ if .Values.unleash.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: 386757133934.dkr.ecr.us-east-1.amazonaws.com/docker-hub/unleashorg/unleash-server
    argocd-image-updater.argoproj.io/update-strategy: semver
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: unleash
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/unleash
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main


  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

    automated:
      prune: true
      enabled: {{ .Values.unleash.autoSync }}
      selfHeal: {{ .Values.unleash.autoSync }}

    syncOptions:
      - CreateNamespace=true

{{ end }}
