{{ if .Values.vpa.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vertical-pod-autoscaler
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: registry.k8s.io/autoscaling/vpa-recommender:^1.4
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/vertical-pod-autoscaler
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: main


  syncPolicy:
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

    automated:
      enabled: {{ .Values.vpa.autoSync }}
      selfHeal: {{ .Values.vpa.autoSync }}
      prune: true

    syncOptions:
      - CreateNamespace=true

{{ end }}
