# nonk8s
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: javier-sandbox
  region: "us-east-1"
  version: "1.32"


availabilityZones: [ "us-east-1a","us-east-1b" ]


managedNodeGroups:
  - name: mng1
    instanceTypes: [ "t2.medium", "m5.xlarge" ] # At least one instance type should be specified
    minSize: 3
    desiredCapacity: 3
    maxSize: 5
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly


nodeGroups:
  - name: ng2
    instancesDistribution:
      instanceTypes: [ "t2.medium", "m5.xlarge" ] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    minSize: 3
    desiredCapacity: 3
    maxSize: 5
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: external-secrets-sa
        namespace: external-secrets
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

    - metadata:
        name: prometheus-sa
        namespace: monitoring
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

    - metadata:
        name: eksctl-sa
        namespace: monitoring
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

    - metadata:
        name: eksctl-sa
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

    - metadata:
        name: eksctl-sa
        namespace: chartmuseum
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
