---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
  name: javier
  region: us-east-1

nodeGroups:
  - name: ng-1
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["m4.xlarge"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    minSize: 2
    desiredCapacity: 3
    maxSize: 4
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true


iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: eksctl-sa
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"


git:
  repo:
    url: "git@github.com:jmatias/eks-sandbox.git"
    email: javier.l.matias@gmail.com
    branch: master
    fluxPath: "flux/"
  operator:
    namespace: "flux"
    withHelm: true
