apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: actions-runner-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    releaseName: actions-runner-controller
    namespace: github-actions
    version: 0.*
    valuesFile: values.yaml

resources:
  - secrets.yaml
