---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: cicd-strawman-runner-deployment
spec:
  replicas: 1
  template:
    spec:
      repository: jmatiascabrera/cicd-strawman

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: eks-sandbox-runner-deployment
spec:
  replicas: 1
  template:
    spec:
      repository: jmatias/eks-sandbox
