apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: github-auth
    creationPolicy: Owner
  data:
    - secretKey: docker-username
      remoteRef:
        key: javier/actions-runner-controller/github
        property: github_token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
  data:
    - secretKey: docker-username
      remoteRef:
        key: javier/docker/jmatiastw
        property: username
    - secretKey: docker-password
      remoteRef:
        key: javier/docker/jmatiastw
        property: password
    - secretKey: docker-email
      remoteRef:
        key: javier/docker/jmatiastw
        property: email
