apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  releaseName: descheduler
  chart:
    repository: https://raw.githubusercontent.com/komljen/helm-charts/master/charts
    name: descheduler
    version: 0.2.1
  values:


    image:
      repository: komljen/descheduler
      tag: v0.8.0
      pullPolicy: IfNotPresent

    schedule: "*/30 * * * *"

    cmdOptions:
      v: 4
      max-pods-to-evict-per-node: 10

    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: false
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution

    rbac:
      create: true

    serviceAccount:
      create: true
