---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: 'true'
    filter.fluxcd.io/chart-image: "semver:>=3.0"
  name: external-secrets
  namespace: kube-system
spec:
  HelmVersion: v3
  releaseName: secret-manager
  chart:
    repository: https://godaddy.github.io/kubernetes-external-secrets
    name: kubernetes-external-secrets
    version: 3.2.0
  wait: false
  timeout: 120
  rollback:
    timeout: 120
    enable: true
  values:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi
    serviceAccount:
      create: false
      name: eksctl-sa
    env:
      AWS_REGION: 'us-east-1'
      LOG_LEVEL: error
      POLLER_INTERVAL_MILLISECONDS: 30000
    securityContext:
      runAsNonRoot: false
      fsGroup: 65534

    serviceMonitor:
      enabled: false
      namespace: external-secrets

    replicaCount: 1


    image:
      repository: godaddy/kubernetes-external-secrets
      tag: 3.3.0
      pullPolicy: IfNotPresent


    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 20
