---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ptv
  namespace: ptv

spec:
  releaseName: ptv
  helmVersion: v3
  chart:
    repository: http://chartmuseum-chartmuseum.chartmuseum
    name: ptv
    version: 0.1.7
  timeout: 300
  wait: true
  rollback:
    timeout: 300
    enable: true
    retry: true
    wait: true
    maxRetries: 0
  values:
    image:
      repository: 745892955196.dkr.ecr.us-east-1.amazonaws.com/ptv
      tag: 0.1.1
      imagePullPolicy: IfNotPresent

    serviceMonitor:
      enabled: false

    headerBackgroundColor: '#1e88e5'
    posgresqlExistingSecret:
      name: unleash-superuser
      usernameKey: pg_su_username
      passwordKey: pg_su_password

    resources:
      requests:
        cpu: 32m
        memory: 32Mi

      limits:
        cpu: 96m
        memory: 96Mi


    replicaCount: 1

    postgresql:
      database: unleash
      url: stolon-proxy.unleash

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      host: ptv.javiermatias.net
      path: /


    service:
      type: ClusterIP
      port: 80

