---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ptv-replication
  namespace: ptv
secretDescriptor:
  backendType: secretsManager
  data:
    - key: ptv/postgres/replication/username/dev
      name: pg_repl_username
    - key: ptv/postgres/replication/password/dev
      name: pg_repl_password


---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ptv-superuser
  namespace: ptv
secretDescriptor:
  backendType: secretsManager
  data:
    - key: ptv/postgres/superuser/username/dev
      name: pg_su_username
    - key: ptv/postgres/superuser/password/dev
      name: pg_su_password
