apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: self-serve-example-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/group.name: "prod-external"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06


spec:
  ingressClassName: alb
  rules:
    - host: self-serve.tw-javier.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: self-serve-example
                port:
                  number: 80
