apiVersion: v1
kind: Service
metadata:
  name: self-serve-example
  annotations:
    external-dns.alpha.kubernetes.io/hostname: self-serve.tw-javier.work
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: self-serve-example
