apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fast-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fast-api
    spec:
      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "poetry", "run","fastapi", "run","src/celery_sandbox/app.py", "--port=5000" ]


          image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
          {{- if ne (lower .Values.environment) "aws" }}
            - name: ROOT_PATH
              value: /api
          {{- end }}

          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
