apiVersion: v1
kind: Service
metadata:
  name: fast-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.tw-ocean.com
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: fast-api
