{{ if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: flower-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flower-ui
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - image: "mher/flower:2.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: celeryflower
          command: [ "celery" ]
          args:
            - "flower"
            - "--host=0.0.0.0"
            - "--logging=DEBUG"
            - "--purge_offline_workers=60"
            - "--port=5555"
            - "--tasks_columns=name,uuid,state,result,received,started,runtime,worker"
          {{ if .Values.environment | eq "aws" }}
            - "--basic_auth=flower:local"
          {{- end}}
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
            - name: FLOWER_BROKER_API
              value: {{ .Values.redis.url }}

          ports:
            - containerPort: 5555
              protocol: TCP

          resources:
          {{- toYaml .Values.resources | nindent 14 }}
{{ end }}
