{{ if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-ui
spec:
  replicas: {{ .Values.flower.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: flower-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flower-ui
        env: dev
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}
      containers:
        - image: "mher/flower:2.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: celery-flower
          command: [ "celery" ]
          args:
            - "flower"
            - "--host=0.0.0.0"
            - "--logging=DEBUG"
            - "--purge_offline_workers=60"
            - "--port=5555"
            - "--tasks_columns=name,uuid,state,result,received,started,runtime,worker"
            {{ if .Values.flower.githubOAuth.enabled }}
            - "--auth_provider=flower.views.auth.GithubLoginHandler"
            - "--auth=javier@javiermatias.com"
            - "--oauth2_key={{ .Values.flower.githubOAuth.auth }}"
            - "--oauth2_secret={{ .Values.flower.githubOAuth.oauth2Key }}"
            - "--oauth2_redirect_uri={{ .Values.flower.githubOAuth.oauth2RedirectUri }}"
            {{ end }}
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
            - name: FLOWER_BROKER_API
              value: {{ .Values.redis.url }}

          ports:
            - containerPort: 5554
              protocol: TCP

          volumeMounts:
            - name: flower-config-volume
              mountPath: /code/conf/flowerconfig.py
              subPath: flowerconfig.py

          resources:
          {{- toYaml .Values.resources | nindent 14 }}

      volumes:
        - name: flower-config-volume
          secret:
            secretName: flower-config
{{ end }}
