{{ if .Values.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-ui
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.flower.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: flower-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flower-ui
        env: fargate
    spec:

      tolerations:
        - key: "spotInstance"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/capacityType
                    operator: In
                    values:
                      - SPOT

      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}

      containers:
        - image: {{ .Values.flower.image.repository }}:{{ .Values.flower.image.tag }}
          imagePullPolicy: {{ .Values.flower.image.pullPolicy }}
          name: celery-flower
          command: [ "celery" ]
          args:
            - "flower"
            - "--host=0.0.0.0"
            - "--logging=DEBUG"
            - "--purge_offline_workers=60"
            - "--port=5555"
            - "--tasks_columns=name,uuid,state,result,received,started,runtime,worker"
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
            - name: FLOWER_BROKER_API
              value: {{ .Values.redis.url }}

            {{ if .Values.flower.githubOAuth.enabled }}
            - name: FLOWER_AUTH_PROVIDER
              value: flower.views.auth.GithubLoginHandler
            - name: FLOWER_AUTH
              value: "javier@javiermatias.com"
            - name: FLOWER_OAUTH2_REDIRECT_URI
              value: {{ .Values.flower.githubOAuth.oauth2RedirectUri }}

            - name: FLOWER_OAUTH2_KEY
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: AUTH_GITHUB_CLIENT_ID
            - name: FLOWER_OAUTH2_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-oauth
                  key: AUTH_GITHUB_CLIENT_SECRET
            {{ end }}

          ports:
            - containerPort: 5555
              protocol: TCP

          resources:
          {{- toYaml .Values.resources | nindent 14 }}


{{ end }}
