apiVersion: v1
data:
  nginx.conf: |
    events{}
    http{
        server {
            listen 5555;

            location /ping {

                proxy_pass http://flower-ui:5554/; # Flower's port
                proxy_set_header Host $host;
            }

            location / {
                set $api_key "none";
                if ($http_x_api_key) {
                    set $api_key $http_x_api_key;
                }

                # Replace this with your actual API key
                if ($api_key != "local") {
                    return 401 "Forbidden: Incorrect API Key";
                }
                proxy_pass http://flower-ui:5554; # Flower's port
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
