apiVersion: v1
kind: Service
metadata:
  name: {{ include "celery-sandbox.name" . }}-redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
