apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worker
        env: dev
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "celery-sandbox.serviceAccountName" . }}
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: worker
          command: [ "poetry", "run", "celery","-A", "celery_sandbox.worker.celery", "worker", "--loglevel=info" ]
          env:
            - name: CELERY_BROKER_URL
              value: {{ .Values.redis.url }}
            - name: CELERY_RESULT_BACKEND
              value: {{ .Values.redis.url }}
