apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "1"
              memory: "1000Mi"
