apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  timeout.reconciliation: "20s"
  kustomize.buildOptions: "--enable-helm"
  resource.exclusions: |
    - apiGroups:
        - "actions.github.com"
      kinds:
        - "AutoscalingListener"
      clusters:
        - "*"
      namespaces:
        - "github-actions"
      name: "javier-k8s-runner*"
