apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  timeout.reconciliation: "20s"
  kustomize.buildOptions: "--enable-helm"
  application.resourceTrackingMethod: annotation
  accounts.javier: apiKey, login
