apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  timeout.reconciliation: "20s"
  kustomize.buildOptions: "--enable-helm"
  application.resourceTrackingMethod: annotation
  accounts.javier: apiKey, login
  accounts.admin: apiKey, login

  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /spec/preserveUnknownFields
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $argocd-secret:dex.github.clientID
          clientSecret: $argocd-secret:dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
          orgs:
          - name: jmatias
