- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --insecure  # Already implied if you're handling TLS at ALB

- op: add
  path: /spec/replicas
  value: 1

- op: add
  path: /spec/template/metadata/annotations
  value:
    reloader.stakater.com/auto: "true"


## Add toleration for spot instances

- op: add
  path: /spec/template/spec/tolerations
  value:
    - key: "spot-instance"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
