apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

patches:
  - path: argocd-cmd-params-cm.yaml
    target:
      name: argocd-cmd-params-cm
  - path: ingress.yaml
    target:
      name: argocd-server-ingress
