apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - github-oauth-secret.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
    target:
      name: argocd-cmd-params-cm

  - path: argocd-cm.yaml
    target:
      name: argocd-cm

  - path: ingress.yaml
    target:
      name: argocd-server-ingress

  - path: service.yaml
    target:
      name: argocd-server
