apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - argocd-vpa.yaml
  - github-oauth-secret.yaml

patches:

  - path: application-controller.yaml
    target:
      kind: StatefulSet
      name: argocd-application-controller

  - path: server-deployment.yaml
    target:
      name: argocd-server
      kind: Deployment

  - path: repo-server-deployment.yaml
    target:
      name: argocd-repo-server
      kind: Deployment

  - path: argocd-cmd-params-cm.yaml
    target:
      name: argocd-cmd-params-cm

  - path: argocd-cm.yaml
    target:
      name: argocd-cm

  - path: ingress.yaml
    target:
      name: argocd-server-ingress

  - path: redis.yaml
    target:
      name: argocd-redis
      kind: Deployment
