---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-postgresql
  namespace: unleash
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: javier/unleash/postgres
        property: POSTGRES_PASSWORD

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-admin
  namespace: unleash
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-admin
    creationPolicy: Owner
  data:
    - secretKey: UNLEASH_DEFAULT_ADMIN_PASSWORD
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_PASSWORD

    - secretKey: UNLEASH_DEFAULT_ADMIN_USERNAME
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_USERNAME

---
