---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unleash-postgresql
  namespace: unleash
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-postgresql
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: javier/unleash/postgres
        property: POSTGRES_PASSWORD
    - secretKey: password
      remoteRef:
        key: javier/unleash/postgres
        property: POSTGRES_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unleash-admin
  namespace: unleash
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-admin
    creationPolicy: Owner
  data:
    - secretKey: UNLEASH_DEFAULT_ADMIN_PASSWORD
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_PASSWORD

    - secretKey: UNLEASH_DEFAULT_ADMIN_USERNAME
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_USERNAME

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
  data:
    - secretKey: docker-username
      remoteRef:
        key: javier/docker/jmatiastw
        property: username
    - secretKey: docker-password
      remoteRef:
        key: javier/docker/jmatiastw
        property: password
    - secretKey: docker-email
      remoteRef:
        key: javier/docker/jmatiastw
        property: email
