---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: unleash
  namespace: unleash
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unleash
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  recommenders:
    - name: frugal
