global:
  defaultStorageClass: gp2
  storageClass: gp2

replicaCount: 1
ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/group.name: "prod-external"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
  hosts:
    - host: "feature-toggles.tw-javier.work"
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

existingSecrets:
  - name: UNLEASH_DEFAULT_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: unleash-admin
        key: UNLEASH_DEFAULT_ADMIN_PASSWORD
  - name: UNLEASH_DEFAULT_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: unleash-admin
        key: UNLEASH_DEFAULT_ADMIN_USERNAME

service:
  type: ClusterIP
  port: 4242
  annotations:
    external-dns.alpha.kubernetes.io/hostname: feature-toggles.tw-javier.work

dbConfig:
  useExistingSecret:
    name: "unleash-postgresql"
    key: "postgres-password"

postgresql:
  auth:
    existingSecret: "unleash-postgresql"
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

env:
  - name: CHECK_VERSION
    value: "false"
  - name: SEND_TELEMETRY
    value: "false"
  - name: UNLEASH_URL
    value: "https://feature-toggles.tw-javier.work"

podLabels:
    env: fargate
