apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:

  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 16.7.27
    releaseName: prometheus-grafana-pg
    namespace: monitoring
    valuesInline:
      global:
        security:
          allowInsecureImages: true
      image:
        registry: 386757133934.dkr.ecr.us-east-1.amazonaws.com/docker-hub
      auth:
        existingSecret: grafana-pg-auth
        username: grafana
        database: grafana
      primary:
        terminationGracePeriodSeconds: 30
        persistence:
          enabled: true
          size: 8Gi
        resources:
          requests: { cpu: 100m, memory: 256Mi }
          limits:   { cpu: 500m, memory: 512Mi }
      readReplicas:
        replicaCount: 2
        resources:
          requests: { cpu: 100m, memory: 256Mi }
          limits:   { cpu: 500m, memory: 512Mi }

  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: monitoring
    valuesFile: values.yaml
    version: 77.1.0


patches:
  - path: grafana.yaml
    target:
      kind: Deployment
      name: prometheus-grafana

resources:
  - secrets.yaml
  - vpa.yaml
  - grafana-dashboard-15661-cm.yaml
