---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: github-oauth
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GITHUB_CLIENT_ID
      remoteRef:
        key: javier/grafana/github-oauth
        property: AUTH_GITHUB_CLIENT_ID

    - secretKey: GF_AUTH_GITHUB_CLIENT_SECRET
      remoteRef:
        key: javier/grafana/github-oauth
        property: AUTH_GITHUB_CLIENT_SECRET


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: javier/grafana/admin
        property: admin-password
    - secretKey: admin-user
      remoteRef:
        key: javier/grafana/admin
        property: admin-user
