---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus-grafana
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  recommenders:
    - name: default

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-grafana-pg-postgresql
  namespace: monitoring
spec:
    targetRef:
        apiVersion: apps/v1
        kind: StatefulSet
        name: prometheus-grafana-pg-postgresql
    updatePolicy:
        updateMode: "Auto"
        minReplicas: 1
    recommenders:
      - name: default

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: prometheus-prometheus-node-exporter
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  recommenders:
    - name: default
