image:
  repository: 386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/sdlc-trace
  pullPolicy: IfNotPresent
  tag: "0.1.6"


serviceAccount:
  create: true
  automount: true
  annotations: { }

resources: {}
#  requests:
#    cpu: 250m
#    memory: 250m

livenessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
startupProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 5

replicas: 2

environment: "aws"

ingress:
  enabled: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: auto-ebs-sc
