image:
  repository: 386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/sdlc-trace
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.6"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: true
  automount: true
  annotations: { }

resources: { }

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
startupProbe:
  httpGet:
    path: /docs
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 30

replicas: 1

environment: "aws"

ingress:
  enabled: true

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: standard
