apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
