installCRDs: true

imagePullSecrets:
  - name: dockerhub-secret

replicaCount: 2
webhook:
  replicaCount: 2
certController:
  replicaCount: 2

tolerations:
  - key: "spotInstance"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
