installCRDs: true

imagePullSecrets:
  - name: dockerhub-secret

replicaCount: 1
webhook:
  replicaCount: 1
certController:
  replicaCount: 1

tolerations:
  - key: "spotInstance"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

serviceAccount:
  create: false
  name: external-secrets-sa
