name: "Run Unit Tests"
description: "Run unit tests"
branding:
  icon: "code"
  color: "yellow"
runs:
  using: "composite"
  steps:
    - run: |
        echo "Running unit tests in ${{inputs.environment}}..."
        sleep ${{inputs.wait}}
      name: Deploy to ${{inputs.environment}}
      shell: bash
