---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-server
  namespace: argocd
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "argocd-server"
        controlledResources: [ "cpu", "memory" ]
#        minAllowed:
#          cpu: 50m
#          memory: "128Mi"
#        maxAllowed:
#          cpu: "1000m"
#          memory: "512Mi"
        controlledValues: RequestsAndLimits
  recommenders:
    - name: default

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: argocd-application-controller
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "argocd-application-controller"
        controlledResources: [ "cpu", "memory" ]
#        minAllowed:
#          cpu: 50m
#          memory: "128Mi"
#        maxAllowed:
#          memory: "512Mi"
#          cpu: "1000m"
        controlledValues: RequestsAndLimits
  recommenders:
    - name: default


---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-repo-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "argocd-repo-server"
        controlledResources: [ "cpu", "memory" ]
#        minAllowed:
#          cpu: 50m
#          memory: "128Mi"
#        maxAllowed:
#          memory: "512Mi"
#          cpu: "1000m"
        controlledValues: RequestsAndLimits
  recommenders:
    - name: default
