---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-secrets
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  recommenders:
    - name: frugal
