apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender-frugal
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-recommender-frugal
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  recommenders:
    - name: frugal
  resourcePolicy:
    containerPolicies:
      - containerName: "recommender"
        controlledResources:
          - cpu
          - memory
        controlledValues: "RequestsAndLimits"
        minAllowed:
          cpu: 50m
          memory: "128Mi"
        maxAllowed:
          memory: "256Mi"

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-recommender
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  recommenders:
    - name: frugal
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources:
          - cpu
          - memory
        controlledValues: "RequestsAndLimits"
        minAllowed:
          cpu: 50m
          memory: "100Mi"
        maxAllowed:
          memory: "256Mi"


---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-updater
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpa-updater
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  recommenders:
    - name: frugal
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources:
          - cpu
          - memory
        controlledValues: "RequestsAndLimits"
        minAllowed:
          cpu: 25m
          memory: "75Mi"
        maxAllowed:
          memory: "128Mi"

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
  recommenders:
    - name: frugal
  resourcePolicy:
    containerPolicies:
      - containerName: "metrics-server"
        controlledResources:
          - cpu
          - memory
        controlledValues: "RequestsAndLimits"
        minAllowed:
          cpu: 50m
          memory: "128Mi"
        maxAllowed:
          memory: "300Mi"
