spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:jmatias/eks-sandbox.git
    targetRevision: main


environment: "aws"

sdlcTrace:
    enabled: true
    autoSync: true
    image:
        tag: 0.3.1

appOfApps:
  enabled: true
  autoSync: true

backstage:
  enabled: false
  autoSync: false
  image:
    tag: 0.9.1

argocd:
  autoSync: true
  ingress:
    enabled: true

prometheus:
  enabled: true
  autoSync: false

celerySandbox:
  enabled: false
  autoSync: true
  image:
    tag: "0.3.0"


albIngressController:
  autoSync: true
