apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: celery-sandbox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: celery-sandbox
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: celery-sandbox
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    retry:
      limit: 3
      backoff:
        duration: "30s"
    syncOptions:
      - CreateNamespace=true
      - Prune=true
      - Validate=true
      - Retry=true
