{{- if eq (lower .Values.environment) "aws" }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.11.0
    helm:
      releaseName: alb-ingress-controller
      valuesObject:
        clusterName: javier-sandbox

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2

{{- end }}
