apiVersion: v1
kind: ConfigMap
data:
  server.insecure: "true"
  server.rootpath: "/argo"
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
