apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: airflow
    repo: https://airflow.apache.org
    releaseName: airflow
    namespace: airflow
    version: 1.*
    valuesFile: values.yaml
