{{ if .Values.actionsRunnerController.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: ghcr.io/actions/gha-runner-scale-set-controller
    argocd-image-updater.argoproj.io/update-strategy: semver
spec:
  destination:
    namespace: github-actions
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/actions-runner-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    kustomize:
      namespace: github-actions

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{- if .Values.actionsRunnerController.autoSync }}
    automated:
      prune: true
      selfHeal: true

    {{- end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
      limit: 10
{{- end }}
