apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.12.1
    helm:
      valuesObject:
        config:
          registries:
            - name: ECR
              api_url: https://386757133934.dkr.ecr.us-east-1.amazonaws.com
              prefix: "386757133934.dkr.ecr.us-east-1.amazonaws.com"
              ping: yes
              default: true
              insecure: false
              credentials: ext:/scripts/ecr-login.sh
              credsexpire: 12h

        authScripts:
          enabled: true
          scripts:
            ecr-login.sh: |
              #!/bin/sh
              aws ecr --region "us-east-1" get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{ if .Values.albIngressController.autoSync   }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
