apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/backstage
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        postgresql:
          global:
            defaultStorageClass: gp2
            storageClass: gp2
          enabled: true
          auth:
            username: backstage
        ingress:
          enabled: false
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: 'ip'
            alb.ingress.kubernetes.io/load-balancer-name: backstage

        backstage:
          replicas: 1
          image:
            registry: 590184073526.dkr.ecr.us-east-1.amazonaws.com
            repository: javier/backstage
            tag: 0.4.4
          extraEnvVarsSecrets:
            - backstage-secrets
            - github-auth

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
