{{ if .Values.backstage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/backstage
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        global:
          {{- if eq (lower .Values.environment) "aws" }}
          defaultStorageClass: gp2
          storageClass: gp2
          {{- end }}
        service:
          type: ClusterIP
          ports:
            backend: 7007
        postgresql:
          global:
            {{- if eq (lower .Values.environment) "aws" }}
            defaultStorageClass: gp2
            storageClass: gp2
            {{- end }}

          enabled: true
          auth:
            username: backstage
        ingress:
          enabled: true
          path: /
          host: "backstage.tw-eks-sandbox.work"
          tls:
            enabled: false
            secretName: "backstage-tls"
          annotations:
            {{- if eq (lower .Values.environment) "aws" }}
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: 'ip'
            alb.ingress.kubernetes.io/load-balancer-name: backstage
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:590184073526:certificate/7cd935d0-21d0-4d38-bfcf-c1fd934ab204
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
            {{ else }}
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/ssl-passthrough: "false"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            {{- end }}

        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: backstage.tw-eks-sandbox.work

        backstage:
          containerPorts:
            backend: 7007
          replicas: 1
          image:
            registry: 590184073526.dkr.ecr.us-east-1.amazonaws.com
            repository: javier/backstage
            tag: 0.8.8
            pullSecrets:
              - ecr-registry-secret
          extraEnvVarsSecrets:
            - backstage-secrets
            - github-auth

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true
    automated:
      selfHeal: true
      prune: true

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

{{- end}}
