{{ if .Values.backstage.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/apps/backstage
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        global:
          {{- if eq (lower .Values.environment) "aws" }}
          defaultStorageClass: gp2
          storageClass: gp2
          {{- end }}
        service:
          type: ClusterIP
          ports:
            backend: 7007
        postgresql:
          global:
            {{- if eq (lower .Values.environment) "aws" }}
            defaultStorageClass: gp2
            storageClass: gp2
            {{- end }}

          enabled: true
          auth:
            username: backstage
        ingress:
          enabled: true
          {{- if eq (lower .Values.environment) "aws" }}
          className: alb
          {{- else }}
          className: nginx
          {{- end }}
          path: /
          host: "backstage.tw-javier.work"
          tls:
            enabled: false
            secretName: "backstage-tls"
          annotations:
            {{- if eq (lower .Values.environment) "aws" }}
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: 'ip'
            alb.ingress.kubernetes.io/group.name: "prod-external"
{{/*            alb.ingress.kubernetes.io/inbound-cidrs: '174.224.252.127/32, 50.217.105.18/32'*/}}
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
            {{ else }}
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/ssl-passthrough: "false"
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            {{- end }}

        service:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: backstage.tw-javier.work

        backstage:
          annotations:
            reloader.stakater.com/auto: "true"
          containerPorts:
            backend: 7007
          replicas: 1
          image:
            registry: 386757133934.dkr.ecr.us-east-1.amazonaws.com
            repository: javier/backstage
            tag: {{ .Values.backstage.image.tag }}
            pullSecrets:
              - ecr-registry-secret
          extraEnvVarsSecrets:
            - postgres-secrets
            - github-oauth

          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/readiness
              port: 7007
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 2
            readinessProbe:

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/liveness
              port: 7007
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/liveness
              port: 7007
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2


  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Prune=true

    {{ if .Values.backstage.autoSync   }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5

{{- end}}
