{{ if .Values.celerySandbox.enabled   }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: celery-sandbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/image-list: fastapi=386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/celery-sandbox,
      worker=386757133934.dkr.ecr.us-east-1.amazonaws.com/javier/celery-sandbox,
      flower=docker.io/mher/flower
    argocd-image-updater.argoproj.io/fastapi.helm.image-tag: fastapi.image.tag
    argocd-image-updater.argoproj.io/fastapi.helm.image-name: fastapi.image.name
    argocd-image-updater.argoproj.io/flower.helm.image-tag: flower.image.tag
    argocd-image-updater.argoproj.io/flower.helm.image-name: flower.image.name
    argocd-image-updater.argoproj.io/worker.helm.image-tag: worker.image.tag
    argocd-image-updater.argoproj.io/worker.helm.image-name: worker.image.name
    argocd-image-updater.argoproj.io/update-strategy: semver
spec:
  destination:
    namespace: celery-sandbox
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: infra/apps/celery-sandbox
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
        flower:
          enabled: true
          replicas: 1

        fastapi:
          enabled: true
          replicas: 1

        worker:
          enabled: true
          replicas: 1

  syncPolicy:
    retry:
      limit: 6
      backoff:
        duration: "30s"

    {{ if .Values.celerySandbox.autoSync }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    syncOptions:
      - CreateNamespace=true

{{ end }}
