{{ if .Values.unleash.enabled   }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD

    - secretKey: postgres-password
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: unleash
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: unleash
    repoURL: https://docs.getunleash.io/helm-charts
    targetRevision: 5.4.3


  syncPolicy:
    retry:
      limit: 6
      backoff:
        duration: "30s"

    {{ if .Values.unleash.autoSync   }}
    automated:
      prune: true
      selfHeal: true
    {{ end }}

    syncOptions:
      - CreateNamespace=true

{{ end }}
