{{ if .Values.unleash.enabled   }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-postgresql
  namespace: unleash
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-postgresql
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD

    - secretKey: postgres-password
      remoteRef:
        key: javier/backstage/postgres
        property: POSTGRES_PASSWORD


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unleash-admin
  namespace: unleash
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: unleash-admin
    creationPolicy: Owner
  data:
    - secretKey: UNLEASH_DEFAULT_ADMIN_PASSWORD
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_PASSWORD

    - secretKey: UNLEASH_DEFAULT_ADMIN_USERNAME
      remoteRef:
        key: javier/unleash/admin
        property: UNLEASH_DEFAULT_ADMIN_USERNAME

---


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unleash
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: unleash
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: unleash
    repoURL: https://docs.getunleash.io/helm-charts
    targetRevision: 5.4.3
    helm:
      valuesObject:
        global:
          defaultStorageClass: gp2
          storageClass: gp2

        ingress:
          enabled: true
          className: "alb"
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: 'ip'
            alb.ingress.kubernetes.io/group.name: "prod-external"
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
            alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
          hosts:
            - host: "unleash.tw-javier.work"
              paths:
                - path: /
                  pathType: Prefix
          tls: [ ]

        existingSecrets:
          - name: UNLEASH_DEFAULT_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: unleash-admin
                key: UNLEASH_DEFAULT_ADMIN_PASSWORD
          - name: UNLEASH_DEFAULT_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: unleash-admin
                key: UNLEASH_DEFAULT_ADMIN_USERNAME

        service:
          type: ClusterIP
          port: 4242
          annotations:
            external-dns.alpha.kubernetes.io/hostname: unleash.tw-javier.work


  syncPolicy:
    retry:
      limit: 6
      backoff:
        duration: "30s"

    {{ if .Values.unleash.autoSync }}
    automated:
      prune: false
      selfHeal: false
    {{ end }}

    syncOptions:
      - CreateNamespace=true

{{ end }}
