global:
#  imageRegistry: "386757133934.dkr.ecr.us-east-1.amazonaws.com"
  imagePullSecrets:
    - name: dockerhub-secret
datahub-frontend:
  imagePullSecrets:
    - name: dockerhub-secret
  image:
    repository: acryldata/datahub-frontend-react
  extraVolumes:
    - name: datahub-users
      secret:
        defaultMode: 0444
        secretName: datahub-users-secret
  extraVolumeMounts:
    - name: datahub-users
      mountPath: /datahub-frontend/conf/user.props
      subPath: user.props

  service:
    type: ClusterIP
    annotations:
      external-dns.alpha.kubernetes.io/hostname: datahub.tw-javier.work
      external-dns.alpha.kubernetes.io/ttl: "60"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: 'ip'
      alb.ingress.kubernetes.io/group.name: "prod-external"
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06

    hosts:
      - host: datahub.tw-javier.work
        paths:
          - /
    pathType: Prefix

  mysqlSetupJob:
    imagePullSecrets:
      - name: dockerhub-secret
    image:
      repository: acryldata/datahub-mysql-setup
    enabled: true
    resources:
      limits:
        cpu: 2500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 256Mi

  datahubUpgrade:
    imagePullSecrets:
      - name: dockerhub-secret
    image:
      repository: acryldata/datahub-upgrade
    enabled: true
    restoreIndices:
      resources:
        limits:
          cpu: 2500m
          memory: 1Gi
        requests:
          cpu: 300m
          memory: 256Mi

  datahubSystemUpdate:
    imagePullSecrets:
      - name: dockerhub-secret
    image:
      repository: acryldata/datahub-upgrade
    resources:
      limits:
        cpu: 3000m
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 2Gi

  elasticsearchSetupJob:
    imagePullSecrets:
      - name: dockerhub-secret
    image:
      repository: acryldata/datahub-elasticsearch-setup
    enabled: true
    resources:
      limits:
        cpu: 2500m
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 256Mi

  kafkaSetupJob:
    imagePullSecrets:
      - name: dockerhub-secret
    image:
      repository: acryldata/datahub-kafka-setup
    enabled: true
    resources:
      limits:
        cpu: 3000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 768Mi
  datahub-gms:
    imagePullSecrets:
      - name: dockerhub-secret
    enabled: true
    image:
      repository: acryldata/datahub-gms
    service:
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: datahub-gms.tw-javier.work
        external-dns.alpha.kubernetes.io/ttl: "60"
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: 'ip'
        alb.ingress.kubernetes.io/group.name: "prod-external"
        alb.ingress.kubernetes.io/healthcheck-path: /health
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:386757133934:certificate/2011e861-aed4-447e-b55c-7d3c56155d37
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06

      hosts:
        - host: datahub-gms.tw-javier.work
          paths:
            - /
      pathType: Prefix
