apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
# additional resources like ingress rules, cluster and repository secrets.
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.10/manifests/install.yaml
#  - base/argocd-cm.yaml

patches:
  - path: overlays/aws/argocd-cm.yaml
  - path: overlays/aws/argocd-cmd-params-cm.yaml
